src/Microsoft.Azure.EventHubs.Processor/AzureStorageCheckpointLeaseManager.cs, test/Microsoft.Azure.EventHubs.Processor.UnitTests/EventProcessorHostTests.cs
Adding basic validation to throw more descriptive error in case of an invalid container name.
=> Adding basic validation for lease container name.

samples/SampleEphReceiver/project.json, samples/SampleSender/project.json, src/Microsoft.Azure.EventHubs.Processor/project.json, src/Microsoft.Azure.EventHubs/project.json, test/Microsoft.Azure.EventHubs.Processor.UnitTests/project.json, test/Microsoft.Azure.EventHubs.UnitTests/project.json
https://docs.microsoft.com/en-us/dotnet/articles/standard/library
Now available on UWP as well.
=> Changing to .NET Standard 1.3

src/Microsoft.Azure.EventHubs.Processor/AzureBlobLease.cs, src/Microsoft.Azure.EventHubs.Processor/Lease.cs, src/Microsoft.Azure.EventHubs.Processor/PartitionManager.cs
Started with 6 failing tests, not sure if those are _just_ flaky or not.
Please review.
=> Switching Lease to async methods where needed

test/Microsoft.Azure.EventHubs.Processor.UnitTests/EventProcessorHostTests.cs, test/Microsoft.Azure.EventHubs.UnitTests/EventHubClientTests.cs
=> Capture xunit output

src/Microsoft.Azure.EventHubs/Amqp/Management/AmqpServiceClient.cs, test/Microsoft.Azure.EventHubs.Processor.UnitTests/EventProcessorHostTests.cs, test/Microsoft.Azure.EventHubs.Processor.UnitTests/NegativeCases.cs, test/Microsoft.Azure.EventHubs.Processor.UnitTests/TestEventProcessor.cs, test/Microsoft.Azure.EventHubs.UnitTests/EventHubClientTests.cs, test/Microsoft.Azure.EventHubs.UnitTests/NegativeCases.cs
* Converting exceptions to MessagingException on AMQP service client.
* Adding EPH with nonexistent entity unit test.
* Moving negative tests to dedicated test classes.
=> Exception conversion at AMQP service client.

test/Microsoft.Azure.EventHubs.UnitTests/EventHubClientTests.cs
Adding unit tests for parallel client operations. Parallel Send and parallel GetRuntimeInformation calls. These tests are looking for possible races and thread safety issues.
=> Adding unit tests for parallel client operations.

test/Microsoft.Azure.EventHubs.UnitTests/EventHubClientTests.cs
- Replacing Task.Factory with Task.Run (advised)
- Removing task unwrapping
- Removing delay that doesn't seem to do anything
=> Simplified code

appveyor.yml, samples/SampleEphReceiver/SampleEphReceiver.xproj, samples/SampleSender/SampleSender.xproj, src/Microsoft.Azure.EventHubs.Processor/Microsoft.Azure.EventHubs.Processor.xproj, src/Microsoft.Azure.EventHubs/Microsoft.Azure.EventHubs.xproj, test/Microsoft.Azure.EventHubs.Processor.UnitTests/Microsoft.Azure.EventHubs.Processor.UnitTests.xproj, test/Microsoft.Azure.EventHubs.Processor.UnitTests/project.json, test/Microsoft.Azure.EventHubs.UnitTests/EventHubClientTests.cs, test/Microsoft.Azure.EventHubs.UnitTests/Microsoft.Azure.EventHubs.UnitTests.xproj, test/Microsoft.Azure.EventHubs.UnitTests/project.json
There are a couple changes here:
1. Changed build output to be default location.
2. Removed connection string output during test run.
3. Updated XUnit to latest.
=> Adding AppVeyor support for CI

src/Microsoft.Azure.EventHubs/Primitives/ClientInfo.cs, src/Microsoft.Azure.EventHubs/project.json
=> Custom preprocessor define NESTANDARD is not needed.

samples/SampleEphReceiver/SimpleEventProcessor.cs, src/Microsoft.Azure.EventHubs.Processor/AzureStorageCheckpointLeaseManager.cs, src/Microsoft.Azure.EventHubs.Processor/EventHubPartitionPump.cs, src/Microsoft.Azure.EventHubs.Processor/EventProcessorHost.cs, src/Microsoft.Azure.EventHubs.Processor/PartitionContext.cs, src/Microsoft.Azure.EventHubs.Processor/PartitionManager.cs, src/Microsoft.Azure.EventHubs.Processor/PartitionPump.cs, src/Microsoft.Azure.EventHubs/Amqp/ActiveClientLinkManager.cs, src/Microsoft.Azure.EventHubs/Amqp/AmqpEventDataSender.cs, src/Microsoft.Azure.EventHubs/Amqp/AmqpEventHubClient.cs, src/Microsoft.Azure.EventHubs/Amqp/AmqpPartitionReceiver.cs, src/Microsoft.Azure.EventHubs/Amqp/Management/AmqpServiceClient.cs, src/Microsoft.Azure.EventHubs/Amqp/Management/DataType.cs, src/Microsoft.Azure.EventHubs/EventHubClient.cs, src/Microsoft.Azure.EventHubs/PartitionReceiver.cs, src/Microsoft.Azure.EventHubs/PartitionSender.cs
=> Using ConfigureAwait(false) to avoid context restoration

src/Microsoft.Azure.EventHubs/Primitives/EventHubsConnectionStringBuilder.cs
=> unnecessary else statements

src/Microsoft.Azure.EventHubs.Processor/AzureStorageCheckpointLeaseManager.cs, src/Microsoft.Azure.EventHubs.Processor/EventProcessorHost.cs, test/Microsoft.Azure.EventHubs.Processor.UnitTests/EventProcessorHostTests.cs
This prefix enables multiple eventhubs to be processed in the same lease container.
=> Wiring up storageBlobPrefix to EPH constructors.

test/Microsoft.Azure.EventHubs.Processor.UnitTests/project.json, test/Microsoft.Azure.EventHubs.UnitTests/project.json
...until we get the build figured out.
=> Reverting the addition of unit tests for .net 4.6

src/Microsoft.Azure.EventHubs/Amqp/AmqpEventHubClient.cs, src/Microsoft.Azure.EventHubs/Amqp/AmqpServiceClient.cs, test/Microsoft.Azure.EventHubs.UnitTests/EventHubClientTests.cs
This is addressing token expiry issue in https://github.com/Azure/azure-event-hubs-dotnet/issues/62
=> Fixing token expiry in ServiceClient.

appveyor.yml, test/Microsoft.Azure.EventHubs.Processor.UnitTests/project.json, test/Microsoft.Azure.EventHubs.UnitTests/project.json
adding config to turn off strong name verification on build server
=> Adding .NET 4.6 unit tests to Appveyor

src/Microsoft.Azure.EventHubs.Processor/PartitionManager.cs, src/Microsoft.Azure.EventHubs/project.json
Integrating the new Nuget release of Azure AMQP.
=> Azure AMQP 2.0.2

build/DeployAzureResources.ps1
Enabling data collection to suppress warning, and also adding entity path to connection string
=> Appveyor Update

src/Microsoft.Azure.EventHubs.Processor/AzureStorageCheckpointLeaseManager.cs, src/Microsoft.Azure.EventHubs.Processor/project.json
+ Bumping up storage Nuget version to 8.0.1
+ Temporarily addressing a storage issue which is tracked at https://github.com/Azure/azure-storage-net/issues/398
=> Bumping up the AzureStorage version to 8.0.1 and addressing a storage issue.

src/Microsoft.Azure.EventHubs/Amqp/AmqpEventDataSender.cs
Previous check-in merged partial. Adding missing file.
=> Fixing build break introduced with preview check-in.

src/Microsoft.Azure.EventHubs.Processor/project.json, src/Microsoft.Azure.EventHubs/Amqp/AmqpMessageConverter.cs, src/Microsoft.Azure.EventHubs/Primitives/ClientInfo.cs, src/Microsoft.Azure.EventHubs/project.json, test/Microsoft.Azure.EventHubs.UnitTests/EventHubClientTests.cs
+ Moving to Azure.AMQP 2.0.4
+ Moving back to .Net451
+ Improving AMQP message convertor to rule out empty message case.
+ Adding message body validation to basic send/receive unit test.
=> AMQP package change and minor perf improvement.

readme.md
Fixed broken links.
Fixing Readme
- [No] **I have read the [contribution guidelines](./CONTRIBUTING.md).**
=> Update readme.md - fixed getting started links

global.json
Specifying .net core version for Appveyor build
=> Updating global.json

src/Microsoft.Azure.EventHubs.Processor/project.json
=> Bumping up the Storage version to 8.1.1

global.json
1.0.0-preview2-003131 is the latest tooling & SDK from .NET Core team. We are moving to this version.
=> Bumping up dependent SDK to latest - 3131.

src/Microsoft.Azure.EventHubs/Primitives/AsyncLock.cs
AsyncLock implementation has some unnecessary pieces from legacy .NET client. Removing them for performance improcement.
=> Slimming down AsyncLock by removing unnecessary checks and calls.

src/Microsoft.Azure.EventHubs.Processor/AzureStorageCheckpointLeaseManager.cs, src/Microsoft.Azure.EventHubs.Processor/LeaseLostException.cs
- Throw LeaseLostException when in-doubt and on known error codes only.
- Throw LeaseLostException with storage exception message.
=> Fix lease-lost decision logic

src/Microsoft.Azure.EventHubs.Processor/Microsoft.Azure.EventHubs.Processor.csproj, src/Microsoft.Azure.EventHubs/Microsoft.Azure.EventHubs.csproj
=> Bumping up the client version to 1.0.3

appveyor.yml, build/build.ps1, readme.md, src/Microsoft.Azure.EventHubs.Processor/AzureStorageCheckpointLeaseManager.cs, src/Microsoft.Azure.EventHubs.Processor/EventHubPartitionPump.cs, src/Microsoft.Azure.EventHubs.Processor/LeaseLostException.cs, src/Microsoft.Azure.EventHubs.Processor/Microsoft.Azure.EventHubs.Processor.csproj, src/Microsoft.Azure.EventHubs.Processor/PartitionPump.cs, src/Microsoft.Azure.EventHubs/Amqp/AmqpClientConstants.cs, src/Microsoft.Azure.EventHubs/Amqp/AmqpEventDataSender.cs, src/Microsoft.Azure.EventHubs/Amqp/AmqpEventHubClient.cs, src/Microsoft.Azure.EventHubs/Amqp/AmqpPartitionReceiver.cs, src/Microsoft.Azure.EventHubs/Amqp/AmqpServiceClient.cs, src/Microsoft.Azure.EventHubs/EventDataBatch.cs, src/Microsoft.Azure.EventHubs/Microsoft.Azure.EventHubs.csproj, src/Microsoft.Azure.EventHubs/Primitives/EventHubsConnectionStringBuilder.cs, src/Microsoft.Azure.EventHubs/Primitives/RetryPolicy.cs, src/Microsoft.Azure.EventHubs/Resources.Designer.cs, test/Microsoft.Azure.EventHubs.Tests/Client/ClientTestBase.cs, test/Microsoft.Azure.EventHubs.Tests/Client/MiscTests.cs, test/Microsoft.Azure.EventHubs.Tests/Client/PartitionPumpTests.cs, test/Microsoft.Azure.EventHubs.Tests/Client/ReceiverTests.cs, test/Microsoft.Azure.EventHubs.Tests/Client/WebSocketTests.cs, test/Microsoft.Azure.EventHubs.Tests/Microsoft.Azure.EventHubs.Tests.csproj, test/Microsoft.Azure.EventHubs.Tests/Processor/NegativeCases.cs, test/Microsoft.Azure.EventHubs.Tests/Processor/ProcessorTestBase.cs, test/Microsoft.Azure.EventHubs.Tests/TestUtility.cs
Cherry picking changes from dev branch to master up to commit f2b194be010212e972336402d9b3784070570ced inclusive.
=> Dev to master

src/Microsoft.Azure.EventHubs.Processor/AzureStorageCheckpointLeaseManager.cs, src/Microsoft.Azure.EventHubs.Processor/EventProcessorHost.cs, src/Microsoft.Azure.EventHubs.Processor/PartitionManagerOptions.cs, test/Microsoft.Azure.EventHubs.Tests/Processor/NegativeCases.cs, test/Microsoft.Azure.EventHubs.Tests/Processor/ProcessorTestBase.cs
PartitionManagerOptions support for EPH. Options provide to customize lease renew interval and lease duration. 
Related to https://github.com/Azure/azure-event-hubs-dotnet/issues/201
=> Adding PartitionManagerOptions

src/Microsoft.Azure.EventHubs/EventHubsDiagnosticSource.cs, src/Microsoft.Azure.EventHubs/PartitionSender.cs, test/Microsoft.Azure.EventHubs.Tests/Client/ClientTestBase.cs, test/Microsoft.Azure.EventHubs.Tests/Client/DiagnosticsTests.cs, test/Microsoft.Azure.EventHubs.Tests/Client/FakeDiagnosticListener.cs, test/Microsoft.Azure.EventHubs.Tests/Microsoft.Azure.EventHubs.Tests.csproj
Improvements to Diagnostic Source instrumentation:
- remove redundant tags
- add instrumentation for ```PartitionSender```
=> [DS] Improve Diagnostic Source instrumentation

src/Microsoft.Azure.EventHubs/EventDataDiagnosticExtensions.cs, src/Microsoft.Azure.EventHubs/EventHubsDiagnosticSource.cs, test/Microsoft.Azure.EventHubs.Tests/Client/DiagnosticsTests.cs, test/Microsoft.Azure.EventHubs.Tests/TestUtility.cs
Added 
- "Diagnostic-Id" and "Correlation-Context" injection to events to cross-correlate producer and consumer
- ```EventData.ExtractActivity()``` helper to create a diagnostic activity based on injected context
Fixes #215.
=> [DS] Added Diagnostic-Id and Correlation-Context injection

src/Microsoft.Azure.EventHubs.Processor/EventProcessorOptions.cs
Aligning InitialOffsetProvider's API description with .NET client.
=> Fixing description of InitialOffsetProvider

readme.md
Replaced "liblaries" with "libraries" 
=> Fixed a typographical error

readme.md
=> Fixing dev branch badge img URL.

src/Microsoft.Azure.EventHubs.Processor/AzureStorageCheckpointLeaseManager.cs, src/Microsoft.Azure.EventHubs.Processor/Microsoft.Azure.EventHubs.Processor.csproj, src/Microsoft.Azure.EventHubs/Microsoft.Azure.EventHubs.csproj
Moving dependency packages to latest versions.
=> Bumping up AMQP and some other Nuget package versions

readme.md, src/Microsoft.Azure.EventHubs.Processor/AzureStorageCheckpointLeaseManager.cs, src/Microsoft.Azure.EventHubs.Processor/Microsoft.Azure.EventHubs.Processor.csproj, src/Microsoft.Azure.EventHubs/Microsoft.Azure.EventHubs.csproj
* Badge fix
* Bump up the dependent packaging versions including Azure.AMQP
=> Merge dev to master

src/Microsoft.Azure.EventHubs.Processor/AzureStorageCheckpointLeaseManager.cs, src/Microsoft.Azure.EventHubs.Processor/Microsoft.Azure.EventHubs.Processor.csproj, src/Microsoft.Azure.EventHubs.Processor/PartitionContext.cs
Merging Newtonsoft.JSON V10 and empty lease offset fixes to master branch for 2.0.1 release.
=> Dev to master for201 release

src/Microsoft.Azure.EventHubs.Processor/PartitionManager.cs, test/Microsoft.Azure.EventHubs.Tests/Client/ReceiverTests.cs
Missed to apply proxy settings to EPH management client in the first PR. This completes it.
=> EPH - enable proxy on management client

src/Microsoft.Azure.EventHubs.Processor/AzureStorageCheckpointLeaseManager.cs, src/Microsoft.Azure.EventHubs.Processor/EventHubPartitionPump.cs, src/Microsoft.Azure.EventHubs.Processor/EventProcessorHost.cs, src/Microsoft.Azure.EventHubs.Processor/PartitionContext.cs, src/Microsoft.Azure.EventHubs.Processor/PartitionManager.cs, src/Microsoft.Azure.EventHubs.Processor/PartitionPump.cs
=> Use entire hostname in the EPH traces and error messages.

src/Microsoft.Azure.EventHubs.Processor/PartitionManager.cs, test/Microsoft.Azure.EventHubs.Tests/TestUtility.cs
Lease renew interval can fall short if storage calls start lagging. Calculate sleep time in the renew loop with time taken in the last attempt.
=> Calculate EPH renew interval

src/Microsoft.Azure.EventHubs.Processor/AzureStorageCheckpointLeaseManager.cs, src/Microsoft.Azure.EventHubs.Processor/BlobErrorCodeStrings.cs, src/Microsoft.Azure.EventHubs.Processor/EventProcessorHostActionStrings.cs, src/Microsoft.Azure.EventHubs.Processor/EventProcessorOptions.cs, src/Microsoft.Azure.EventHubs.Processor/PartitionManager.cs, src/Microsoft.Azure.EventHubs/EventData.cs
* Renew leases in parallel 
* Prioritize renewing leases in partition manager loop.
* Handle race between checkpointing and partition manager lease loop.
=> Partition manager lease handling improvements

src/Microsoft.Azure.EventHubs.Processor/EventHubPartitionPump.cs, src/Microsoft.Azure.EventHubs.Processor/EventProcessorHost.cs, src/Microsoft.Azure.EventHubs.Processor/PartitionManager.cs, test/Microsoft.Azure.EventHubs.Tests/Client/TokenProviderTests.cs, test/Microsoft.Azure.EventHubs.Tests/Processor/ProcessorTestBase.cs
=> AAD Token Provider support for EPH

src/Microsoft.Azure.EventHubs.Processor/AzureStorageCheckpointLeaseManager.cs, src/Microsoft.Azure.EventHubs.Processor/EventProcessorHost.cs, src/Microsoft.Azure.EventHubs.Processor/Microsoft.Azure.EventHubs.Processor.csproj, src/Microsoft.Azure.EventHubs/Microsoft.Azure.EventHubs.csproj, test/Microsoft.Azure.EventHubs.Tests/Client/DiagnosticsTests.cs, test/Microsoft.Azure.EventHubs.Tests/Microsoft.Azure.EventHubs.Tests.csproj, test/Microsoft.Azure.EventHubs.Tests/Processor/ProcessorTestBase.cs
Extending Storage provider on EPH for full MSI support.
Clients will be able to provide CloudStorageAccount which supports AAD/MSI token provider scenarios.
=> Support Azure Storage AAD/MSI token provider at EPH instantiation.

src/Microsoft.Azure.EventHubs/Amqp/AmqpPartitionReceiver.cs
Service Fabric calls OnChangeRoleAsync() while AmqpPartitionReceiver's OnReceiveAsync is still active
Bug #295
=> Fix closing the receiver can cause FabricNotPrimaryException exception

src/Microsoft.Azure.EventHubs.Processor/PartitionManager.cs
If owned lease is expired somehow then we should not double count it.
=> Avoid double counting of owned and expired leases.

src/Microsoft.Azure.EventHubs.Processor/PartitionManager.cs
EPH to provide inner exception to caller if storage access fails.
=> Provide last exception when all retries exhausted.

src/Microsoft.Azure.EventHubs.Processor/AzureStorageCheckpointLeaseManager.cs
https://github.com/Azure/azure-storage-net has a class to validate all the entities that azure storage manage.
I think it'd be handy to delegate the check to the library because.
- We already have the reference to it.
- If the rule change this package doesn't have to change anything.
- This package can still handling the error to throw a custom error message instead the internal one.
- This can avoid unit test to check the logic in this package.
=> Change LeaseContainerName Validation

src/Microsoft.Azure.EventHubs.Processor/PartitionContext.cs, src/Microsoft.Azure.EventHubs.Processor/PartitionManager.cs, src/Microsoft.Azure.EventHubs.Processor/PartitionPump.cs, src/Microsoft.Azure.EventHubs/Amqp/ActiveClientLinkObject.cs, src/Microsoft.Azure.EventHubs/Amqp/AmqpEventDataSender.cs, src/Microsoft.Azure.EventHubs/Amqp/AmqpExceptionHelper.cs, src/Microsoft.Azure.EventHubs/Amqp/AmqpPartitionReceiver.cs, src/Microsoft.Azure.EventHubs/Amqp/AmqpServiceClient.cs, src/Microsoft.Azure.EventHubs/Amqp/SerializationUtilities.cs, src/Microsoft.Azure.EventHubs/Primitives/ManagedServiceIdentityTokenProvider.cs, src/Microsoft.Azure.EventHubs/Primitives/SecurityToken.cs, src/Microsoft.Azure.EventHubs/Primitives/TimeoutHelper.cs
I've changed some things as proposition, **Please feel free to ignore this PR if you thing that it does not make sense at all.**
- https://github.com/DGenix/azure-event-hubs-dotnet/commit/6ecce32daf18fb7f306d8f1bb39c8ee05955d213#diff-919bb1df8b20959701a137f4fe88722eR107
(I've changed the params format for those line with more than 180 columns)
- https://github.com/DGenix/azure-event-hubs-dotnet/commit/6ecce32daf18fb7f306d8f1bb39c8ee05955d213#diff-919bb1df8b20959701a137f4fe88722eR154
Use name of instead
- https://github.com/DGenix/azure-event-hubs-dotnet/commit/6ecce32daf18fb7f306d8f1bb39c8ee05955d213#diff-096b5b8dd0baf0e08e478d6e490d541bR226
This should be cancelled in case the token is, isn't it? …
=> Suggested code cleanups

src/Microsoft.Azure.EventHubs.ServiceFabricProcessor/EventProcessorService.cs
GetServiceParitionId operated under the assumption that the full ranged list could be iterated through to count partitions. Replaced with a lookup that doesn't throw when this isn't the case  (e.g. low and high key aren't long.MinValue and long.MaxValue, respectively). It still performs the original function of determining the number of partitions available and identifying which partition the service is running on.
No original unit tests to modify, but ran it through on my system with a more limited range (0 to 65535) without an issue.
=> Improved approach to handling partition counting/identification

src/Microsoft.Azure.EventHubs.Processor/PartitionManager.cs
=> Parallelize expired lease check in processor host

src/Microsoft.Azure.EventHubs.Processor/PartitionManager.cs
Just a very small PR to pass a missing cancellation token to the `Task.Run()`
@serkantkaraca 
I was reading this method because I was running a code factor you can check the results here.
https://www.codefactor.io/repository/github/davidrevoledo/azure-event-hubs-dotnet/issues
and seem that the complexity for this method it's too high I don't know your opinion about split it.
=> Complete Missing CancellationToken

test/Microsoft.Azure.EventHubs.Tests/Client/NegativeCases.cs
=> Max message size is 1MB now. Updating the test accordingly.

src/Microsoft.Azure.EventHubs/Primitives/Guard.cs, test/Microsoft.Azure.EventHubs.Tests/Client/NegativeCases.cs
Fix for a few tests failing here https://github.com/Azure/azure-event-hubs-dotnet/pull/339#issuecomment-439969703
=> Fix Exception Type expected in Tests 

src/Microsoft.Azure.EventHubs/Amqp/AmqpClientConstants.cs, src/Microsoft.Azure.EventHubs/Amqp/AmqpServiceClient.cs, src/Microsoft.Azure.EventHubs/EventHubPartitionRuntimeInformation.cs, test/Microsoft.Azure.EventHubs.Tests/Client/ReceiverRuntimeMetricsTests.cs
Adding EventHubPartitionRuntimeInformation.IsEmpty
=> Support partition-empty in runtime metrics

src/Microsoft.Azure.EventHubs/EventData.cs
* Making SystemProperties public
=> Changes for addressing testability issues of API

src/Microsoft.Azure.EventHubs.Processor/Microsoft.Azure.EventHubs.Processor.csproj, src/Microsoft.Azure.EventHubs/Microsoft.Azure.EventHubs.csproj
=> Bumping up the SDK version
