Azure/azure-event-hubs-dotnet

src/Microsoft.Azure.EventHubs.Processor/project.json
src/Microsoft.Azure.EventHubs/project.json

Bumping up client version. Let's keep this as targetted version and bump it up once client published on Nuget.

Bumping up client version. 

---

src/Microsoft.Azure.EventHubs/Amqp/AmqpExceptionHelper.cs
test/Microsoft.Azure.EventHubs.Processor.UnitTests/EventProcessorHostTests.cs
test/Microsoft.Azure.EventHubs.UnitTests/EventHubClientTests.cs

- EPH tests to unregister the active hosts at the end of the run otherwise existing hosts keep interfering with next tests. This is addressing the issue tracked by https://github.com/Azure/azure-event-hubs-dotnet/issues/21
- Improving exception contrat to handle nonexistent consumer group case.

Fix eph unit tests and exception contract

---

src/Microsoft.Azure.EventHubs/Amqp/Management/AmqpServiceClient.cs
test/Microsoft.Azure.EventHubs.Processor.UnitTests/EventProcessorHostTests.cs
test/Microsoft.Azure.EventHubs.UnitTests/EventHubClientTests.cs

+ Use ConcurrentDictionary on static typeCache. AmqpClient is crashing with NullRef when multiple instances are initiated around the same time.
+ Don't checkpoint in the second host in InitialOffsetProviderOverrideBehavior unit test.
+ ReceiveTimeout test to use the same time diff during validation.

Type cache concurrency

---

src/Microsoft.Azure.EventHubs.Processor/project.json
src/Microsoft.Azure.EventHubs/project.json

Disable publicSign in project.json which is causing build failures on Linux and Mac.

Disable publicSign

---

src/Microsoft.Azure.EventHubs/Amqp/AmqpEventHubClient.cs
src/Microsoft.Azure.EventHubs/project.json

System.Net.Security 4.0.0 is not UWP compliant. Removing this legacy dependency since it is not used.

Removing system net security dependency.

---

src/Microsoft.Azure.EventHubs/Primitives/EventHubsConnectionStringBuilder.cs
test/Microsoft.Azure.EventHubs.UnitTests/EventHubClientTests.cs

Client provides a better way of accepting custom domain name from developer. 
Adding 2 more unit tests covering connection string builder usage.

Improving ConnectionStringBuilder experience by enabling custom domain name.

---

src/Microsoft.Azure.EventHubs/Primitives/EventHubsConnectionStringBuilder.cs
test/Microsoft.Azure.EventHubs.UnitTests/EventHubClientTests.cs

Replacing 'namespace' parameter with endpointAddress in the constructor. This way we don't have to hardcode 'servicebus.windows.net' default domain.

Improve connection string builder to accept endpoint domain

---

test/Microsoft.Azure.EventHubs.Processor.UnitTests/project.json
test/Microsoft.Azure.EventHubs.UnitTests/project.json

Unit test config update. Added Microsoft.NetCore.Platforms reference, and apparently order matters in the frameworks section. To say it is finicky is an understatement.

Unit Test Discovery

---

src/Microsoft.Azure.EventHubs.Processor/PartitionManager.cs
test/Microsoft.Azure.EventHubs.Processor.UnitTests/EventProcessorHostTests.cs
test/Microsoft.Azure.EventHubs.UnitTests/EventHubClientTests.cs

Small change for unit tests to save couple minutes while discovering end of stream information on the partitions. Since we now have GetPartitionRuntimeInformation API on the client, we start leveraging this instead of  walking through entire stream to reach the end.

Employ get partition runtime info for discovering end of stream.

---

src/Microsoft.Azure.EventHubs/Primitives/ClientConstants.cs

1 second is falling short for the last retry while working with large messages. .NET client is also using 5 seconds as this buffer. Short tolerance buffer is causing AMQP layers to be called with sub second values.

Increasing timer tolerance buffer in RetryPolicy

---

src/Microsoft.Azure.EventHubs/PartitionReceiver.cs
test/Microsoft.Azure.EventHubs.Processor.UnitTests/EventProcessorHostTests.cs
test/Microsoft.Azure.EventHubs.UnitTests/EventHubClientTests.cs

Adding EndOfStream receiver support and related unit tests.

Adding EndOfStream receiver support

---

src/Microsoft.Azure.EventHubs.Processor/EventHubPartitionPump.cs
src/Microsoft.Azure.EventHubs.Processor/ProcessorEventSource.cs

NetCore Diagnostics.Tracing doesn't allow object type arguments. Converting @startAt argument to string type.

Fixing EPH tracing issue at PartitionPumpCreateClientsStart trace

---

src/Microsoft.Azure.EventHubs.Processor/project.json
src/Microsoft.Azure.EventHubs/Amqp/AmqpEventDataSender.cs
src/Microsoft.Azure.EventHubs/project.json

Support for .NET Framework 4, 4.5, and 4.5.1 ended on January 12, 2016. Moving framework dependency to 4.5.2

Moving net framework to 452

---

src/Microsoft.Azure.EventHubs.Processor/AzureStorageCheckpointLeaseManager.cs
src/Microsoft.Azure.EventHubs.Processor/LeaseLostException.cs

LeaseLostException needs to know just the partition-id. Don't hand over the entire lease.

Remove lease object from LeaseLostException

---

src/Microsoft.Azure.EventHubs.Processor/PartitionContext.cs

ContinueWith throws TaskCancelledException when blob call fails due to lease lost. Removing ContinueWith for simplifying error handling.

Fix checkpoint exception handling at lease lost case.

---

src/Microsoft.Azure.EventHubs/Amqp/AmqpClientConstants.cs
src/Microsoft.Azure.EventHubs/Amqp/AmqpEventDataSender.cs
src/Microsoft.Azure.EventHubs/Amqp/AmqpPartitionReceiver.cs
src/Microsoft.Azure.EventHubs/Primitives/AsyncLock.cs
test/Microsoft.Azure.EventHubs.UnitTests/EventHubClientTests.cs

AMQP session create can take a little longer than typical Send or Receive call since it might involve first time TCP connection creation. Because of this allowing a minimum duration for session creation makes sense.

Allow at least 60 seconds for AMQP session create.

---

src/Microsoft.Azure.EventHubs/Amqp/AmqpEventDataSender.cs
src/Microsoft.Azure.EventHubs/Amqp/AmqpPartitionReceiver.cs

Active client link's audience was set from the absolute URI of the endpoint. For entity level SAS this was causing wrong audience and token renewal to fail eventually. This change is fixing the issue by setting the correct audience required for entity level SAS.
Addressing the issue reported at https://github.com/Azure/azure-event-hubs-dotnet/issues/134

Fix audience on the ActiveClientLink

---

src/Microsoft.Azure.EventHubs/Amqp/AmqpEventHubClient.cs
src/Microsoft.Azure.EventHubs/Primitives/EventHubsConnectionStringBuilder.cs
src/Microsoft.Azure.EventHubs/Resources.Designer.cs
src/Microsoft.Azure.EventHubs/Resources.resx
test/Microsoft.Azure.EventHubs.Tests/Client/ConnectionStringBuilderTests.cs
test/Microsoft.Azure.EventHubs.Tests/Client/MiscTests.cs
test/Microsoft.Azure.EventHubs.Tests/Client/TimeoutTests.cs

Client will support SharedAccessSignature name in the connection string with this change.

Adding shared access signature support.

---

src/Microsoft.Azure.EventHubs.Processor/EventHubPartitionPump.cs
src/Microsoft.Azure.EventHubs.Processor/PartitionPump.cs
src/Microsoft.Azure.EventHubs/Amqp/AmqpPartitionReceiver.cs
src/Microsoft.Azure.EventHubs/Amqp/AmqpServiceClient.cs

When awaiting for an async method, by default context is captured and attempted to be restored. Since this is a library, it could be used from UI or non-UI code. W/o specifying .ConfigureAwait(false) there will be some overhead of attempting to restore the context. To avoid that, awaited code should explicitly specifying not to restore the context.
Related issue #41 #39

Using ConfigureAwait(false) to avoid context restoration

---

appveyor.yml
build/build.ps1
readme.md

Adding encrypted secrets for Appveyor build integration.

Fix appveyor.yml

---

test/Microsoft.Azure.EventHubs.Tests/Client/WebSocketTests.cs

Missed to close sender and receiver at the end of new unit test which is causing intermittent failures in other tests when max receiver limit is hit.

Close sender and receiver clients in web-sockets unit test.

---

src/Microsoft.Azure.EventHubs/Amqp/AmqpPartitionReceiver.cs
test/Microsoft.Azure.EventHubs.Tests/Client/ClientTestBase.cs
test/Microsoft.Azure.EventHubs.Tests/Client/MiscTests.cs
test/Microsoft.Azure.EventHubs.Tests/Client/PartitionPumpTests.cs
test/Microsoft.Azure.EventHubs.Tests/Client/ReceiverTests.cs
test/Microsoft.Azure.EventHubs.Tests/Processor/NegativeCases.cs
test/Microsoft.Azure.EventHubs.Tests/Processor/ProcessorTestBase.cs
test/Microsoft.Azure.EventHubs.Tests/TestUtility.cs

Close pump call might race with next Set call where client ends up with closed pump after reregistering.
This fix moves the Close call from pump task to SetReceiveHandler. 
The issue is reported and discussed at https://github.com/Azure/azure-event-hubs-dotnet/issues/173

Fixing receiver pump open/close race issue

---

src/Microsoft.Azure.EventHubs/Amqp/AmqpClientConstants.cs
src/Microsoft.Azure.EventHubs/Amqp/AmqpEventDataSender.cs
src/Microsoft.Azure.EventHubs/Amqp/AmqpPartitionReceiver.cs

Small or large operation timeout values doesn't really work well with create session calls. Therefore moving to a fixed timeout.

Using a fixed timeout while creating AMQP session.

---

readme.md

* Fixing Appveyor badge link
* Adding a reminder to install .Net Cross Platform SDK in order to build clients on VS 2017

Fix Appveyor badge link and add VS 2017 build instructions.

---

src/Microsoft.Azure.EventHubs/Amqp/AmqpEventDataSender.cs
src/Microsoft.Azure.EventHubs/Amqp/AmqpPartitionReceiver.cs
src/Microsoft.Azure.EventHubs/EventDataSender.cs
src/Microsoft.Azure.EventHubs/EventHubClient.cs
src/Microsoft.Azure.EventHubs/PartitionReceiver.cs
src/Microsoft.Azure.EventHubs/Primitives/ClientEntity.cs
src/Microsoft.Azure.EventHubs/Primitives/RetryExponential.cs
src/Microsoft.Azure.EventHubs/Primitives/RetryPolicy.cs
test/Microsoft.Azure.EventHubs.Tests/Client/RetryTests.cs

This change allows retry policy to be specialized on child entities like senders and receivers. For example with this change, when both senders and receivers are created from the same client, senders can have RetryPolicyExponential while receivers have NoRetry. 
Change aligns .Net Standard client with .Net client's retry policy.

Client entities should inherit retry policy from parent client.

---

src/Microsoft.Azure.EventHubs/Primitives/EventHubsConnectionStringBuilder.cs
test/Microsoft.Azure.EventHubs.Tests/Client/ConnectionStringBuilderTests.cs

When supplying SharedAccessSignature as a parameter
Fixes #288 (https://github.com/Azure/azure-event-hubs-dotnet/issues/218)

Fix EventHubsConnectionStringBuilder ctor crash with SharedAccessSignature

---

src/Microsoft.Azure.EventHubs.Processor/Microsoft.Azure.EventHubs.Processor.csproj

Some number of Azure Services still depend on V10 and V11 seems to be a breaking move for them. Moving back to V10.0.3.

Reducing Newtonsoft.Json dependency version to 10.0.3

---

src/Microsoft.Azure.EventHubs.Processor/AzureStorageCheckpointLeaseManager.cs
src/Microsoft.Azure.EventHubs.Processor/PartitionContext.cs

Lease might have empty offset data stored if there were no events on the partitions. This fix handles such cases.

Fixing empty offset from no-receive partition lease.

---

src/Microsoft.Azure.EventHubs.Processor/PartitionManager.cs

EPH client isn't providing partitionId when storage call fails on renew or acquire call. This fix addresses that issue.

Notify partitionId in the error callback if lease call fails.

---

src/Microsoft.Azure.EventHubs/Amqp/AmqpEventDataSender.cs
src/Microsoft.Azure.EventHubs/Amqp/AmqpPartitionReceiver.cs
src/Microsoft.Azure.EventHubs/Amqp/AmqpServiceClient.cs

Move AmqpClientConstants.AmqpSessionTimeoutInSeconds to Receive call. This way default timeout will be respected through the AMQP session create stack.
+ Fixing timeouts used in AMQP management calls.

Always use default timeout for AMQP sesssion create.

---

src/Microsoft.Azure.EventHubs/Amqp/AmqpMessageConverter.cs
test/Microsoft.Azure.EventHubs.Tests/Amqp/AmqpMEssageCoverterTests.cs

copy properties from an amqp message into the the event data system
properties collection when updating the event data headers and
properites.
- follow the code style from Azure EH Amqp dotnet: https://github.com/Azure/azure-amqp/blob/9b421a7ebee725196507b64d1feab8950a079859/Microsoft.Azure.Amqp/Amqp/Framing/Properties.cs#L65
- add some coverage that helps to test and understand how to reprod
resolved: #242

Fix correlation id not received from IotHub EH endpoint

---

src/Microsoft.Azure.EventHubs.Processor/Microsoft.Azure.EventHubs.Processor.csproj
src/Microsoft.Azure.EventHubs/Microsoft.Azure.EventHubs.csproj
test/Microsoft.Azure.EventHubs.Tests/Microsoft.Azure.EventHubs.Tests.csproj

+ Bumping up SDK version to 2.2.0
+ Always delay sign assemblies

Bumping up SDK version to 2.2.0 for release

---

src/Microsoft.Azure.EventHubs/Amqp/AmqpExceptionHelper.cs
src/Microsoft.Azure.EventHubs/Amqp/AmqpPartitionReceiver.cs
src/Microsoft.Azure.EventHubs/Primitives/EventHubsTimeoutException.cs
test/Microsoft.Azure.EventHubs.Tests/Client/TimeoutTests.cs

For consistency I've craeted EventHubsTimeOutException Trasient as true as default.
Reference. https://github.com/Azure/azure-event-hubs-dotnet/issues/176

Create EventHubsTimeoutException for consistency

---

src/Microsoft.Azure.EventHubs/Amqp/AmqpEventHubClient.cs
test/Microsoft.Azure.EventHubs.Tests/Client/PluginTests.cs

@serkantkaraca for this
https://github.com/Azure/azure-event-hubs-dotnet/pull/324
Here the client create other send and lose the Plugins, 
I've copy them in the method you can see in the change, what do you think of this approach, any other better way to do that ? 
https://github.com/Azure/azure-event-hubs-dotnet/blob/4fc6c60288c1c38dc89aca8424ae2a4c24ecfe25/src/Microsoft.Azure.EventHubs/EventHubClient.cs#L51

Fix Build for Plugin_without_ShouldContinueOnException_should_throw Failing

---

test/Microsoft.Azure.EventHubs.Tests/Client/PluginTests.cs

As we move from a list to a concurrent Dictionary to register the plugins for a client it does not make sense ensure that all the plugin will run in order I think as it is not a guarantee as any thread can register them.
If this feature is required anytime I think we can enforce to a Dictionary with a Order and lock anytime a plugin is being added to ensure it is registered in order and will be executed in order was well. 
For the moment I think is best keep it simple until some need that. 
What do you think ? @serkantkaraca 
Also renamed `FirstSendPlugin` just to `SamplePlugin`

Remove unit test and rename FirstPlugin

---

src/Microsoft.Azure.EventHubs/Primitives/Fx.cs

Very small PR to change the static initialization for  `ExceptionUtility` to a Lazy 
https://docs.microsoft.com/en-us/dotnet/framework/performance/lazy-initialization
I think it's not necessary a thread guarantee for this but it won't harm and the package won't lose anything using it.

Using Lazy instead of static initialization for ExceptionUtility 

---

src/Microsoft.Azure.EventHubs/Primitives/Fx.cs

Lazy Load empty delegate only works if the ctor is public which is not the case so it will fix the UT who is failing

Fix LazyLoad Ctor

---

src/Microsoft.Azure.EventHubs/Amqp/AmqpEventHubClient.cs
src/Microsoft.Azure.EventHubs/EventHubClient.cs

- Acording to this is not really safe the double lock pattern w/o volatile at the bottom of the link is the official reference, here  is the change to replace specifically in `AmqpEventHubClient` for a Lazy instead.
Reference : https://help.semmle.com/wiki/display/CSHARP/Double-checked+lock+is+not+thread-safe
**AmqpEventHubClient Code CleanUps :** 
- Remove internal to a few static methods that are only using privately  this will help if we can expose an interface for testing purpose
-  In OnGetPartitionRuntimeInformationAsync / OnGetRuntimeInformationAsync remove await and return task instead
- Create common Constructor to avoid repeated code in both ctors

Replace Locks in AmqpEventHubClient and Code Clean ups in AmqpEventHubClient

---

src/Microsoft.Azure.EventHubs.Processor/AzureStorageCheckpointLeaseManager.cs

- In `AzureStorageCheckpointLeaseManager` `GetAllLeases` 
`GetPartitionIdsAsync` is being used with Result this can wrap aggregated exceptions so this is a suggestion to avoid those type of exceptions by calling with Task.Run the async method and GetAwaiter and GetResult to Unwrap exceptions
- Aling Code in `AzureStorageCheckpointLeaseManager`

Remove Result for AzureStorageCheckpointLeaseManager GetAllLeases

---

src/Microsoft.Azure.EventHubs/EventHubClient.cs
test/Microsoft.Azure.EventHubs.Tests/Amqp/AmqpMEssageCoverterTests.cs

Null check is not neccesary the problem is that Policy is using the Retry before call the initialization so moving at the top of the ctor solve the problem
if the lazy inner is null at that moment there is other bug so I think null check will not make so much sense.
@serkantkaraca 

Fix Tests Moving Lazy initialization at the top of the ctor

---

src/Microsoft.Azure.EventHubs.Processor/AzureStorageCheckpointLeaseManager.cs
src/Microsoft.Azure.EventHubs.Processor/EventProcessorHost.cs
src/Microsoft.Azure.EventHubs.Processor/LeaseLostException.cs
src/Microsoft.Azure.EventHubs.Processor/PartitionContext.cs
src/Microsoft.Azure.EventHubs/Amqp/AmqpMessageConverter.cs
src/Microsoft.Azure.EventHubs/EventDataBatch.cs
src/Microsoft.Azure.EventHubs/EventDataDiagnosticExtensions.cs
src/Microsoft.Azure.EventHubs/EventHubClient.cs
src/Microsoft.Azure.EventHubs/EventPosition.cs
src/Microsoft.Azure.EventHubs/PartitionSender.cs
src/Microsoft.Azure.EventHubs/Primitives/ClientEntity.cs
src/Microsoft.Azure.EventHubs/Primitives/EventHubsConnectionStringBuilder.cs
src/Microsoft.Azure.EventHubs/Primitives/ExceptionUtility.cs
src/Microsoft.Azure.EventHubs/Primitives/Guard.cs
src/Microsoft.Azure.EventHubs/Primitives/RetryPolicy.cs
src/Microsoft.Azure.EventHubs/Primitives/SharedAccessSignatureToken.cs
src/Microsoft.Azure.EventHubs/Primitives/SharedAccessSignatureTokenProvider.cs
src/Microsoft.Azure.EventHubs/Primitives/TokenProvider.cs

To be in the same page as others azure libraries it'd be good to avoid lines to improve legibility  by checking pre null conditions in a easy way.
This is only a proposition as `Guard` class seems to do the same as `ExceptionUtilities` so probabily that code can be there instead or Move the code in Guard to `Fx`.
Open to suggestions to change it or feel free to close if this don't follow the package guidelines. 
- All using are in order BTW 

Use Guard Class to improve code legibility and avoid lines

---

src/Microsoft.Azure.EventHubs/Amqp/AmqpPartitionReceiver.cs

Throwing while handling in catch block causing failfast due to recent change of wiring cancellation token to Task.Delay call. This change is now causing EPH to crash during partition balancing attempts.

Omit failures in receive pump during exception handling

---

src/Microsoft.Azure.EventHubs.Processor/AzureStorageCheckpointLeaseManager.cs
src/Microsoft.Azure.EventHubs.Processor/PartitionManager.cs
src/Microsoft.Azure.EventHubs/Primitives/ExceptionUtility.cs
src/Microsoft.Azure.EventHubs/Primitives/TaskExtensions.cs
test/Microsoft.Azure.EventHubs.Tests/Client/ClientTestBase.cs
test/Microsoft.Azure.EventHubs.Tests/Processor/ProcessorTestBase.cs

I've found 3 more Results in the code in a sync context.
so I propose 1 utility class to handle from now to the future w/o thinking in AggregateExceptions.
-2 of them are in the tests so it's not really a big problem
-1 was in a lambda so I just completed async there
- I've changed also the recent change in `AzureStorageCheckpointLeaseManager` to use this utility 
The idea if the change is accepted is using always this instead of `Result` or manual `GetAwaiter().GetResult()`

Clean more results in sync context

---

src/Microsoft.Azure.EventHubs/EventDataBatch.cs

The list of Event Data in a batch object should be publicly accessible to aligh SDK with .NET and Java.

Provide batch object's event data enumerator publicly.
